### ISSUE TITLE
What is the "+" sign doing here?

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/SlotMachineExercise#13]
https://github.com/andulica/SlotMachineExercise/blob/4961ef6ebdeca455904c48898e25141c18629662/Program.cs#L37
https://github.com/andulica/SlotMachineExercise/blob/4961ef6ebdeca455904c48898e25141c18629662/Program.cs#L54

**Comment by andulica** [comment]
it was meant to be += . It adds up the credits left from previous spins and adds them with the new amount. This block is being executed only if the credits are not enough for the new lines that the players wants to play
