### ISSUE TITLE
Duplicated code

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/SlotMachineExercise#15]
Those two blocks basically to the same things just with different variable names:
https://github.com/andulica/SlotMachineExercise/blob/4961ef6ebdeca455904c48898e25141c18629662/Program.cs#L39-L42
https://github.com/andulica/SlotMachineExercise/blob/4961ef6ebdeca455904c48898e25141c18629662/Program.cs#L58-L61

and even this is doing some of the things:
https://github.com/andulica/SlotMachineExercise/blob/4961ef6ebdeca455904c48898e25141c18629662/Program.cs#L24-L25

And all of those are in the same loop.
Try if you can rearrange your code to make it less repetitive which helps very much to easier understand what is going on

**Comment by andulica** [comment]
By mistake I pushed the commit for issue #18 with the solution to this issue as well. Tried to delete it so that I could split into 2 separate commits but couldn't do it
