### ISSUE TITLE
numbering variables or functions is less descriptive than text

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/SlotMachineExercise#18]
https://github.com/andulica/SlotMachineExercise/blob/4961ef6ebdeca455904c48898e25141c18629662/GameLogic.cs#L76
https://github.com/andulica/SlotMachineExercise/blob/4961ef6ebdeca455904c48898e25141c18629662/GameLogic.cs#L86

It is hard to determine which is Diagonal 1 and 2 and difficult to remember... instead you should prefer the specifics of the line with for example diagonalTopLeft and diagonalTopRight to indicate the start position. 

In case you decide to use enums for the line selection (mentioned in #16) you could also merge those two functions and integrate a condition that decides which diagonal to check base on the given selected line

**Comment by andulica** [comment]
I don't understand how using enums for line selection could simplify my code by combining both checkDiagonal functions into one. Can you elaborate a bit , please

**Comment by incredibleLeitman** [comment]
Your solution by renaming the functions is ok 👍 

What I meant was that you could pass the enum that contains the information what lines to play to a generic "CheckLines" function or at least to a "CheckDiagonalLines" function that has conditions for which cells to compare depending on the given enum:
```
LineSelection lines = ... // return an enum for the lines to play like ALL_HOR, ALL_VER, DIAG_TL, and so on...

// either use a generic function that has code for all line types
int matchedLines = CheckMathingLines(grid, lines);

// or use one method that covers both diagonal lines
if (lines == DIAG_TL || lines == DIAG_TR)
  int matchedLines = CheckDiagonalLines(grid, lines);
```

The code within this CheckDiagonalLines could look something like
``` 
private static int checkDiagonalLines(int[,] grid, LineSelection lines)
{
  if (lines == DIAG_TL)
    return (twoDArray[0, 0] == twoDArray[1, 1] && twoDArray[0, 0] == twoDArray[2, 2]) ? 1 : 0;
 else if (lines == DIAG_TR)
   return (twoDArray[0, 2] == twoDArray[1, 1] && twoDArray[0, 2] == twoDArray[2, 0]) ? 1 : 0;
 else
   throw new Exception($"Invalid line selection for diagonals: {lines}");
}
```

**Comment by andulica** [comment]
So the whole purpose of this is to make the code more scalable and easier to debug? Not going to lie that I spent 30 minutes trying to wrap my head around your solution and still does not fully make sense to me. I will come back to this and draw with pen and paper XD

**Comment by andulica** [comment]
Opened back this issue because I did manage to revert the commit , somehow.. this issue together with issue #15 where pushed in a single commit. Sorry for the mind fuck , hope it makes sense
