### ISSUE TITLE
Forcing the user to enter "start" is really tedious and error prone

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/SlotMachineExercise#2]
https://github.com/andulica/SlotMachine-exercise/blob/3858cc1c86fa01890dec7b46a7bcf92d25006979/SlotMachineExercise/Program.cs#L46-L68

especially if the prompt is kinda confusing xD
" If not , enter Start: " really fked me up and I didn't know what the program wants... why is there a space before the comma? Why is Start with an uppercase and the same as Enter, is this meant to be a key? 🤣 
Usually, if you want to put an exact text to the console you embed it into two " like
```Console.WriteLine("enter \"start\" to begin...");

But usually you don't let users enter a full word as a command to trigger something in your program.
Maybe you can instead if the user does not enter anything at all just start?

**Comment by andulica** [comment]
I found a better solution by asking the user to enter either "y" or "n" (as a yes or no) or type "exit" to exit the game. I believe that is less error prone. Also I could add that on a normal Slot Machine you would have a much better UI with buttons to do different stuff and here I am kind of limited to the console. Please let me know if you think that I could try a better approach. Thanks

**Comment by incredibleLeitman** [comment]
I think you should go for only one letter confirmation and assume every other entered value defaulting to some other behaviour.

For example, in the line selection you could just accept valid integers as lines to play and every other input stops the input (or first trigger the confirmation) without having the text "press 'n'"

Same goes for the output "Do you really want to exit the choosing lines process ? If so, press 'y' or press 'n' to continue choosing more lines" where you in code actually only check for "y" -> So you could only inform the user "y" is exit, any key for continue

For "If you wish to continue with the same gamble, please press 'y.' \nAlternatively, if you prefer to modify your playing values, press 'n'.\n To exit the game type 'exit'" I also would let the user enter "m" or something to modify the values, otherwise continue with the same configuration. You don't really need an user input for exit as the user can always just close the console window or press Ctrl+C to exit
