### ISSUE TITLE
minor: output for diagonal 7 shows extra characters

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/SlotMachineExercise#20]
https://github.com/andulica/SlotMachineExercise/blob/4961ef6ebdeca455904c48898e25141c18629662/GUI.cs#L39-L52

Instead you could print it like this
```" \n          \\        /   " +```

**Comment by andulica** [comment]
you don't want to know that it took me around 20 minutes to do '\\'  :))  learning process is painful
