### ISSUE TITLE
This should not be in GUI as it is a purely logic function

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/SlotMachineExercise#21]
https://github.com/andulica/SlotMachineExercise/blob/4961ef6ebdeca455904c48898e25141c18629662/GUI.cs#L10-L23

Also you don't really need to create a new Random generator everytime you call this function
```Random rnd = new Random(); ```

You could make this a static readonly value (just like a constant but for variables created with "new") so it only gets created once for your entire program

**Comment by incredibleLeitman** [comment]
and btw, you are aware that loop variable can be named other than "i" and "j" right? :D

usually for manipulating values in a grid "row" and "col" are very common because they have the same length and are very descriptive

**Comment by andulica** [comment]
I just got used to name loop variables like that but I can see that what you suggest make the code more readable

**Comment by incredibleLeitman** [comment]
Method is still in GUI instead of GameLogic 👆
