### ISSUE TITLE
duplicated code

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/SlotMachineExercise#29]
https://github.com/andulica/SlotMachineExercise/blob/15ec8e85779015ee78fb0a2e1edec120cc3555ca/Program.cs#L9-L11
https://github.com/andulica/SlotMachineExercise/blob/15ec8e85779015ee78fb0a2e1edec120cc3555ca/Program.cs#L16-L30

You have the code for choosing lines, selecting money to play and populating the grid before and within your game loop, which is not necessary. You could either reorder your statements a little bit to put all of them within the actual loop (because those are definitely the ones you want to iterate as long as the player wants to continue playing) or maybe use a do-while loop that executes the body at least once and after that checks the condition?

**Comment by andulica** [comment]
I spent around an hour and I still don't see what is the problem that you are pointing out. From my point of view in this code all I am doing is instantiating the values outside the loop because I don't want to keep instantiate new objects with every run of the loop and inside the loop I am just updating them. All I am saying is that I don't see any duplicate and if you could please explain me a little bit more in depth I will appreciate

**Comment by incredibleLeitman** [comment]
The reason is that you call
```List<int> linesToPlay = GUI.ChooseLines();```
before ```int credits = GUI.MoneyToPlay(linesToPlay);```
outside of your loop which are *also called inside*, thus the duplicated code mentioning.

This also makes your code flow harder to read, because what it the user enters all lines to play, then enter an amount of money of 1 and then gets asked again to enter money.

The problem, is more obvious for the "GameLogic.PopulateGrid()" method -> you create a fully populated grid which you never use just to do it again within the loop.

> I don't want to keep instantiate new objects with every run of the loop and inside the loop I am just updating them
This is just not true because you "PopulateGrid" function creates a new int array anyway when called :p

But there is nothing wrong with declaring a variable that you plan to use before your loop like
```
List<int> linesToPlay;
while (true)
  linesToPlay = ...
```

**Comment by andulica** [comment]
thanks, now I understand what you meant with the initial statement. I will get it done
