### ISSUE TITLE
Better User Experience

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/SlotMachineExercise#31]
I think you could spent some effort on better ux:

for example before asking the user to choose lines you could again display the valid options.
Currently I feel like there is missing something if the user gets asked to play again and the program just accepts another input

Also from within your main function if the users credits gets below the linesToPlay threshold I would inform the user that there are not enough credits before asking for the money to play

**Comment by andulica** [comment]
Please correct me if you think improvements on this topic would benefit me. In my opinion having to do all the GUI in the console is not getting me any benefits. Would be better if I would be using some proper GUI tools where I can create a better and more intuitive UI and I would not be constrained and limited by the console.

**Comment by incredibleLeitman** [comment]
I don't really understand your last comment? 🤔 
This issue was just to make your program easier to follow for the user how it works and what he is supposed to enter.

Of course a real graphical ui would be nice, but has less to do with programming than just designing, clicking and moving things around. 
We will cover this however using blazor which allows to build applications with a gui using the browser :D

**Comment by andulica** [comment]
I think that some things get lost on the way in our communication process and I am thinking that it might be because we just talk through messages. Now I am not suggesting that we should talk face to face but rather just making a point. Part of what I said was that I thought that you were referring that I need to make major improvements on UI

**Comment by incredibleLeitman** [comment]
You can of course always attend one of the live calls if you feel like communication is getting lost or tag us in the whatsapp group, our channels are always open for you :D

My point with this issue was to make your program a little more user friendly and increasing user experience. This is hard to get right as a developer because you know how your program is working and at what point what inputs are expected and in which format,
but try to take the perspective of an unqualified user that just uses your program for the first time. 

You seem to get the idea and already closed this issue so this is fine :D 👍
