### ISSUE TITLE
Use xml comments

### ISSUE THREAD

**Issue by mayisa87** [andulica/SlotMachineExercise#35]
https://github.com/andulica/SlotMachineExercise/blob/d32946f45d5bd65c3d635d781dd42cdc01ba9013/GameLogic.cs#L19

Instead of doing simple comments, use XML method comments.

See the video here: [XML comments](https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560452)

**Comment by andulica** [comment]
Don't get me wrong , but is it really necessary to write in XML? I can see that is specific to .NET stack but I don't want to perform on my future jobs with C# and .NET

**Comment by mayisa87** [comment]
It is not about XML indeed, in C# the method comments are done this way, and you should get used to do it in right way.
Did you watch the video about it? The difference about just doing // and using the exact method documentation is, that the detailed documentation will be shown to developers when hovering over the method. And this is the very important point.
So even if other languages may wouldn't use XML, you should stick to the habbit documenting your methods.

**Comment by andulica** [comment]
I haven't watched the video because apparently I don't have access
