### ISSUE TITLE
no magic numbers -> 8 could be anything

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/SlotMachineExercise#5]
https://github.com/andulica/SlotMachine-exercise/blob/3858cc1c86fa01890dec7b46a7bcf92d25006979/SlotMachineExercise/Program.cs#L49-L57

0 is ok because this is kinda seen as a special value in most cases,
but the plain 8 can be anything and also needs to be manually adapted if you later would decide to support additional lines.

Especially if you use some exact values twice (here in the condition and the corresponding console prompt) you should define a variable or better constant to be able to rely on one source of truth (there is also a video about that in your Trello board)

**Comment by andulica** [comment]
I encountered  some clashes with the commits on this project and I didn't managed to fix them so I created a new project and fixed issues #5 and #4 and also I got rid of most of the white spaces and I optimised a bit the line checking logic. Could you "transfer" the other issues to my new slotmachine exercise ? please

**Comment by incredibleLeitman** [comment]
Sorry @andulica I am not able to move issues between projects... I am not even sure if github supports this?

But instead of creating a new project you should have solved the errors in this one. You don't always have the opportunity to just start a fresh project and should be able to fix such issues. Maybe you can attend one of the next live calls and show us what went wrong and we guide you through the process of resolving them :D
