### ISSUE TITLE
Remove empty lines and add brakets

### ISSUE THREAD

**Issue by mayisa87** [andulica/SlotMachineExercise#50]
https://github.com/andulica/SlotMachineExercise/blob/c18c5c3452a7f895a31aabf1ecf7e44ef1d35f7e/GUI.cs#L101-L102

I saw it on some places in code, always remove blank lines in your code before committing to github.
There is a video how to add an keyboard-shortcut for this in Visual Studio.  

https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560205

In general, you could use here only else without condition, as if validNumber is not true, so the if does not match, it can anyway be only false. So go for one of this solutions.

```
if (validNumber)
{
...
}
else
{
...
}
```

or

```
if (validNumber)
{
...
}

if (!validNumber)
{
....
}
```

https://github.com/andulica/SlotMachineExercise/blob/c18c5c3452a7f895a31aabf1ecf7e44ef1d35f7e/GUI.cs#L111-L112
Always use curly brakets also if there is only one statement like here in the else block. It will bite you in the ass if you wanna add more logic later on, and forget to use it, as the else block would stopp after first statement/line in else-block!

**Comment by andulica** [comment]
by mistake I submit the fixed code for this problem like this  # 50 . I attach the SHA for that commit here 7602c4c3f11fa0d146d1464aa5b1375d16f73a03
