### ISSUE TITLE
printScreen is not a good name and uses magic numbers

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/SlotMachineExercise#7]
https://github.com/andulica/SlotMachineExercise/blob/4961ef6ebdeca455904c48898e25141c18629662/GUI.cs#L55-L66

Please stick to the common coding conventions and start Methods with uppercase letters 👆 
Also, this method does not print a Screen but rather displays the given grid on the console! (same applies for "populateScreen")

Instead of using magic numbers "3" you could also utilize the created constants you already use for populating the grid
which makes your program consistent if you want to change them

**Comment by andulica** [comment]
Coming from a Java background where naming convention for methods is camel case made me write them that way. But I appreciate your input and is a good thing to know

**Comment by incredibleLeitman** [comment]
Yeah I mean we don't really look that much at coding conventions because this is something that really depends on the language or the codebase and the company you are working for,
but it is important that your code stays consistent. 

And as all "helper functions" in C# starts with an uppercase letter (Console.X, rand.Next, ...) this looks like a hard style break and just triggers my OCD xD

The main learning here is just to stay consistent and adapt to the codebase
