### ISSUE TITLE
Instead of catching an exception your could use TryParse

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/SlotMachineExercise#9]
https://github.com/andulica/SlotMachineExercise/blob/4961ef6ebdeca455904c48898e25141c18629662/GUI.cs#L79-L94

in this block you catch every exception and regardless what happend assume that the input was not valid which is kinda a shotgun approach: if anything goes wrong fix it by trying again xD

Instead you should always handle specific error cases in a certain manor.
For example here you could just try to parse the given input and if it is not correct you can be sure this was not a number using TryParse:
https://learn.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-7.0

**Comment by andulica** [comment]
Immediately after I saw what you said on this issue made me truly realise the code logic mistake and I thought of a solution. Instead catching all errors, just catch the FormatException which in our context is what really interests us and use the TryParse on the try code block. So sort of making the best of your approach and mine if we are on the same page. If we are not , please correct me

**Comment by andulica** [comment]
I think TryParse would be redundant and leaving the line inside the try block "chooseLine = Convert.ToInt32(Console.ReadLine());" as it is

**Comment by incredibleLeitman** [comment]
You are absolutely right by just catching the exception that is interesting in the current context 👍 

However, you usually don't want to use exception handling for flow control 👆 
There is a video in Module 8 about that: "Exception Handling 3 - don't use it for control flow"

If you really want to try to parse some input and in case this goes wrong take another specific, predefined path you can easily rewrite your code to use TryParse instead, which instantly show the reader the intention of the block, 
instead of relying on a try-catch that looks like to something, but in case this explodes try another thing.

```
bool validNumber = Int32.TryParse(Console.ReadLine(), out chosenLine);
if (validNumber == false)
{
  Console.WriteLine("Do you really want to exit the choosing lines process ? If so, press 'y'");
  String userChecker = Convert.ToString(Console.ReadLine());
  if (userChecker.Equals("y"))
  {
    finish = false;
    break;
  }
  else
    continue;
}
```
